-- NL4 Current Generation player profile editor
-- Run once in Supabase SQL Editor. Safe to re-run.

create table if not exists public.nl4_current_player_profiles (
  slug text primary key,
  image_url text,
  content jsonb not null default '{}'::jsonb,
  is_published boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.nl4_current_player_profiles enable row level security;

drop policy if exists "Public can read published current player profiles" on public.nl4_current_player_profiles;
create policy "Public can read published current player profiles"
on public.nl4_current_player_profiles for select
to anon, authenticated
using (is_published = true or auth.role() = 'authenticated');

drop policy if exists "Authenticated admin can insert current player profiles" on public.nl4_current_player_profiles;
create policy "Authenticated admin can insert current player profiles"
on public.nl4_current_player_profiles for insert
to authenticated
with check (true);

drop policy if exists "Authenticated admin can update current player profiles" on public.nl4_current_player_profiles;
create policy "Authenticated admin can update current player profiles"
on public.nl4_current_player_profiles for update
to authenticated
using (true) with check (true);

insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('saka','https://i.postimg.cc/s2Kzy1sX/433177-1684155052.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "BUKAYO", "hero_name_line2": "SAKA", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE MAN BEHIND", "main_title_line2": "THE STAR.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "Bukayo Ayoyinka Temidayo Saka"}, {"label": "Born", "value": "September 5, 2001 – Ealing, London, England"}, {"label": "Position", "value": "Right winger / forward"}, {"label": "Height", "value": "1.78 m (5 ft 10 in)"}, {"label": "International", "value": "England"}, {"label": "Nickname", "value": "Star Boy"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE BUKAYO SAKA STORY", "stories": [{"title": "Hale End & Early Rise", "body": "Saka joined Arsenal''s Hale End Academy at the age of\n                        eight. His technical ability, balance, intelligence,\n                        and humility quickly marked him out as a special talent.\n                        He made his professional debut for Arsenal in November\n                        2018 against Vorskla Poltava."}, {"title": "Arsenal Career", "body": "Saka developed into one of Arsenal''s most important\n                        attacking players. His dribbling, crossing, movement,\n                        and goal contributions have made him a central figure\n                        in the club''s modern resurgence. He won the FA Cup in\n                        2020 and two FA Community Shields."}, {"title": "England & International Stage", "body": "Saka made his England debut in October 2020. He played\n                        in England''s run to the UEFA Euro 2020 final, scored\n                        three goals at the 2022 FIFA World Cup, and continued\n                        to play an important role for England at UEFA Euro 2024."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "THE FUTURE", "legacy_title_line2": "IS ALREADY HERE.", "legacy_body": "From Hale End to the Emirates Stadium, Bukayo Saka represents\n                the talent, identity, and ambition of Arsenal''s modern era.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('ode','https://i.postimg.cc/76HXSZvx/w640xh480-Getty-Images-2080739797.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "MARTIN", "hero_name_line2": "ØDEGAARD", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE CAPTAIN", "main_title_line2": "BEHIND THE VISION.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "Martin Ødegaard"}, {"label": "Born", "value": "December 17, 1998 – Drammen, Norway"}, {"label": "Position", "value": "Attacking midfielder"}, {"label": "Height", "value": "1.78 m (5 ft 10 in)"}, {"label": "Captain", "value": "Arsenal & Norway"}, {"label": "Role", "value": "Creative midfielder"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE ØDEGAARD STORY", "stories": [{"title": "Teenage Prodigy", "body": "Ødegaard emerged as one of Norway''s greatest teenage\n                        talents. At just 15, he became the youngest player and\n                        goalscorer in Norway''s top division before earning a\n                        senior international debut."}, {"title": "Real Madrid to Arsenal", "body": "He signed for Real Madrid in 2015 and gained valuable\n                        experience through loan spells with Heerenveen, Vitesse,\n                        and Real Sociedad. He joined Arsenal on loan in January\n                        2021 before making the move permanent later that year."}, {"title": "Captain & Leader", "body": "Named Arsenal captain in 2022, Ødegaard became one of\n                        Mikel Arteta''s most influential players. His precise\n                        passing, pressing, spatial awareness, and creativity\n                        have made him a key part of Arsenal''s positional play."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "LEAD WITH", "legacy_title_line2": "VISION.", "legacy_body": "Martin Ødegaard''s journey from teenage prodigy to Arsenal\n                captain represents the growth, patience, and ambition of the\n                modern Gunners.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('rice','https://i.postimg.cc/hvTt1cRJ/357662-1687962936.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "DECLAN", "hero_name_line2": "RICE", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE ENGINE", "main_title_line2": "BEHIND THE MIDFIELD.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "Declan Rice"}, {"label": "Born", "value": "January 14, 1999 – Kingston upon Thames, England"}, {"label": "Position", "value": "Midfielder"}, {"label": "Height", "value": "1.88 m (6 ft 2 in)"}, {"label": "International", "value": "England"}, {"label": "Nickname", "value": "Rice Rice Baby"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE DECLAN RICE STORY", "stories": [{"title": "West Ham Rise", "body": "Rice joined Chelsea''s academy at seven before being\n                        released at 14. He later developed at West Ham United,\n                        making his Premier League debut in 2017 and becoming\n                        one of the club''s most important players."}, {"title": "Arsenal Record Signing", "body": "Rice joined Arsenal in July 2023 for £105 million,\n                        becoming the club''s record signing. Under Mikel Arteta,\n                        he developed into a versatile box-to-box midfielder,\n                        combining defensive recovery with attacking influence."}, {"title": "England & Recognition", "body": "After representing the Republic of Ireland before\n                        switching allegiance, Rice became a regular for\n                        England. His progressive passing, interceptions,\n                        physicality, and ball-carrying have established him\n                        as one of Europe''s leading midfielders."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "POWER.", "legacy_title_line2": "COMPOSURE. PURPOSE.", "legacy_body": "Declan Rice has quickly become one of the foundations of\n                Arsenal''s modern midfield and a symbol of the club''s ambition.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('saliba','https://i.postimg.cc/T1s3r0w2/495666-1718697201.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "WILLIAM", "hero_name_line2": "SALIBA", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE DEFENDER", "main_title_line2": "BUILT FOR THE MODERN GAME.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "William Alain André Gabriel Saliba"}, {"label": "Born", "value": "2001 – Bondy, France"}, {"label": "Position", "value": "Centre-back"}, {"label": "Height", "value": "1.93 m (6 ft 4 in)"}, {"label": "International", "value": "France"}, {"label": "Nickname", "value": "Rolls Royce"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE WILLIAM SALIBA STORY", "stories": [{"title": "Early Development", "body": "Saliba began at AS Bondy before developing through\n                        FC Montfermeil and AS Saint-Étienne. Initially a\n                        forward, he transitioned into defence and developed\n                        exceptional athleticism, tactical intelligence,\n                        and composure."}, {"title": "Arsenal & Loans", "body": "Arsenal signed Saliba in July 2019 and allowed him to\n                        continue his development through loan spells at\n                        Saint-Étienne, Nice, and Marseille. His 2021–22 season\n                        at Marseille earned him Ligue 1 Young Player of the\n                        Year recognition and a place in the Ligue 1 Team of\n                        the Year."}, {"title": "France & Recognition", "body": "After returning to Arsenal in 2022, Saliba became a\n                        first-team regular and formed an important defensive\n                        partnership with Gabriel Magalhães. He also became\n                        an important member of the France national team."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "CALM UNDER", "legacy_title_line2": "PRESSURE.", "legacy_body": "William Saliba embodies the pace, composure, athleticism, and\n                technical quality expected from a modern Arsenal defender.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('gabby','https://i.postimg.cc/c19Ht4YT/Getty-Images-2194095253.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "GABRIEL", "hero_name_line2": "MAGALHÃES", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE WALL", "main_title_line2": "AT THE BACK.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "Gabriel dos Santos Magalhães"}, {"label": "Born", "value": "December 19, 1997 – São Paulo, Brazil"}, {"label": "Position", "value": "Centre-back"}, {"label": "Height", "value": "1.91 m (6 ft 3 in)"}, {"label": "International", "value": "Brazil"}, {"label": "Nickname", "value": "Big Gabby"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE GABRIEL MAGALHÃES STORY", "stories": [{"title": "Early Career", "body": "Gabriel began his youth career at Avaí in Brazil,\n                        making his senior debut in 2016. He later moved to\n                        Lille in France, with loan spells at Troyes and\n                        Dinamo Zagreb helping him develop into a commanding\n                        central defender."}, {"title": "Arsenal Career", "body": "Arsenal signed Gabriel in September 2020. He quickly\n                        established himself in Mikel Arteta''s starting\n                        lineup, becoming an important defensive leader and\n                        a major threat from set pieces."}, {"title": "Brazil & Defensive Partnership", "body": "Gabriel earned his senior Brazil call-up in 2023.\n                        At Arsenal, his partnership with William Saliba has\n                        become central to the club''s defensive strength,\n                        combining physical aggression with composure and\n                        technical quality."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "STRENGTH.", "legacy_title_line2": "PASSION. PRIDE.", "legacy_body": "Gabriel Magalhães has become one of the faces of Arsenal''s\n                defensive resurgence and an important pillar of the modern\n                Gunners.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('kai','https://i.postimg.cc/FHtJ1H5w/AFCKaigoal-j3dqjnli.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "KAI", "hero_name_line2": "HAVERTZ", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE PLAYER", "main_title_line2": "BETWEEN THE LINES.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "Kai Lukas Havertz"}, {"label": "Born", "value": "June 11, 1999 – Aachen, Germany"}, {"label": "Position", "value": "Forward / attacking midfielder"}, {"label": "Height", "value": "1.93 m (6 ft 4 in)"}, {"label": "International", "value": "Germany"}, {"label": "Role", "value": "Forward / false nine"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE KAI HAVERTZ STORY", "stories": [{"title": "Bayer Leverkusen Rise", "body": "Havertz developed through Alemannia Mariadorf and\n                        Alemannia Aachen before joining Bayer Leverkusen''s\n                        academy. He made his Bundesliga debut at 17 and quickly\n                        became one of Germany''s most exciting young talents."}, {"title": "Chelsea & Champions League Glory", "body": "Havertz joined Chelsea in 2020. He became a club\n                        history-maker by scoring the winning goal in the\n                        2021 UEFA Champions League Final against Manchester\n                        City and later scored in the FIFA Club World Cup Final."}, {"title": "Arsenal Role", "body": "Havertz joined Arsenal in 2023. Initially used in\n                        midfield, he increasingly found his role as a forward,\n                        where his height, aerial ability, movement, and\n                        finishing became important elements of Arsenal''s attack."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "DIFFERENT.", "legacy_title_line2": "VERSATILE. DECISIVE.", "legacy_body": "Kai Havertz brings a unique blend of size, intelligence,\n                technique, and versatility to Arsenal''s modern attack.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
insert into public.nl4_current_player_profiles (slug,image_url,content,is_published)
values ('nelly','https://i.postimg.cc/ydTM5P0R/london-england-gabriel-martinelli-of-arsenal-celebrates-scoring-his-teams-first-goal-during.jpg','{"hero_eyebrow": "ARSENAL / CURRENT GENERATION", "hero_name_line1": "GABRIEL", "hero_name_line2": "MARTINELLI", "hero_intro": "ARSENAL / CURRENT GENERATION", "hero_button": "Explore the story ↓", "main_eyebrow": "THE COMPLETE STORY", "main_title_line1": "THE SPEED", "main_title_line2": "OF THE GUNNERS.", "facts_eyebrow": "PLAYER ARCHIVE", "facts_title": "AT A GLANCE", "facts": [{"label": "Full Name", "value": "Gabriel Teodoro Martinelli Silva"}, {"label": "Born", "value": "June 18, 2001 – Guarulhos, Brazil"}, {"label": "Position", "value": "Left winger / forward"}, {"label": "Height", "value": "1.78 m / 73 kg"}, {"label": "International", "value": "Brazil"}, {"label": "Nickname", "value": "Gabby"}], "story_eyebrow": "02 / HIS JOURNEY", "story_title": "THE MARTINELLI STORY", "stories": [{"title": "From Futsal to Arsenal", "body": "Martinelli began playing futsal before developing at\n                        Ituano in Brazil. He made his professional debut at\n                        16 before Arsenal signed him in July 2019. His first\n                        season included 10 goals and an FA Cup winner''s medal."}, {"title": "Development Under Arteta", "body": "After recovering from a knee injury, Martinelli\n                        established himself as an important part of Mikel\n                        Arteta''s system. From the left wing, his acceleration,\n                        pressing, direct running, and finishing became major\n                        weapons for Arsenal."}, {"title": "Brazil & International Career", "body": "Martinelli chose to represent Brazil internationally.\n                        He won Olympic gold with Brazil''s under-23 team at\n                        Tokyo 2020, later making his senior debut and featuring\n                        at the 2022 FIFA World Cup and 2024 Copa América."}], "legacy_eyebrow": "NORTH LONDON FOREVER", "legacy_title_line1": "PACE.", "legacy_title_line2": "PASSION. FEARLESSNESS.", "legacy_body": "Gabriel Martinelli represents the intensity and attacking\n                energy of Arsenal''s modern generation, combining speed,\n                determination, and relentless work rate.", "back_button": "← Back to Arsenal Players"}'::jsonb,true)
on conflict (slug) do nothing;
