(function(){'use strict';
const db=window.nl4Supabase,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let fixtures=[],current,lineups=[],events=[],lineupTeam='',editLineup,editEvent;
const fields=[['Possession %','home_possession','away_possession','.1'],['Shots','home_shots','away_shots','1'],['Shots on target','home_shots_on_target','away_shots_on_target','1'],['Corners','home_corners','away_corners','1'],['Corner goals','home_corner_goals','away_corner_goals','1'],['Fouls','home_fouls','away_fouls','1'],['Offsides','home_offsides','away_offsides','1'],['Saves','home_saves','away_saves','1']];
const comparisonFields=[['Matches','matches',1],['Wins','wins',1],['Draws','draws',1],['Losses','losses',1],['Goals for','goals_for',1],['Goals against','goals_against',1],['Points','points',1],['Average possession %','possession_average','.1'],['Shots','shots',1],['Shots on target','shots_on_target',1],['Corners','corners',1],['Corner goals','corner_goals',1],['Fouls','fouls',1],['Offsides','offsides',1],['Saves','saves',1],['Yellow cards','yellow_cards',1],['Red cards','red_cards',1]];
$('stats').innerHTML=fields.map((x,i)=>`<div class="stat"><input id="sh${i}" type="number" min="0" step="${x[3]}"><span>${x[0]}</span><input id="sa${i}" type="number" min="0" step="${x[3]}"></div>`).join('');const val=(id,v)=>$(id).value=v??'',read=id=>$(id).value,num=id=>read(id)===''?null:Number(read(id)),msg=(id,s,b=false)=>{$(id).textContent=s;$(id).style.color=b?'#ff8993':'#8df0b2'},names=()=>({home:current.home_team||(current.is_home?'Arsenal':current.opponent),away:current.away_team||(current.is_home?current.opponent:'Arsenal')});
async function syncApi(){const b=$('syncApi');if(!b||!db)return;b.disabled=true;b.textContent='Syncing…';try{const {data,error}=await db.functions.invoke('sync-ucl-football',{body:{}});if(error)throw error;if(data&&data.error)throw new Error(data.error);b.textContent='API Sync Complete ✓';await loadFixtures();if(current){current=fixtures.find(f=>f.id===current.id)||current;await Promise.all([loadLineups(),loadEvents(),loadComparison()]);}setTimeout(()=>b.textContent='Sync from API-Football',2500)}catch(e){b.textContent='Sync Failed — Retry';alert('Champions League API sync failed: '+(e.message||e))}finally{b.disabled=false}}
function addSyncButton(){const list=$('list');if(!list||$('syncApi'))return;const b=document.createElement('button');b.id='syncApi';b.className='primary';b.type='button';b.textContent='Sync from API-Football';b.style.marginBottom='12px';b.onclick=syncApi;list.parentElement.insertBefore(b,list)}
async function loadFixtures(){const r=await db.from('fixtures').select('*').eq('season','2026/27').eq('competition','UEFA Champions League').order('matchday');if(r.error)return $('list').textContent=r.error.message;fixtures=r.data||[];$('list').innerHTML=fixtures.map(f=>`<article class="match"><div><strong>MD${f.matchday} • ${esc(f.home_team)} vs ${esc(f.away_team)}</strong><div class="meta">${new Date(f.kickoff_at).toLocaleString()} • ${esc(f.venue||'TBC')} • ${esc(f.status)}</div></div><button class="primary edit" data-fixture="${f.id}">Manage</button></article>`).join('')}
async function openFixture(id){current=fixtures.find(f=>f.id===id);if(!current)return;const n=names();$('editor').hidden=false;$('title').textContent=`MD${current.matchday} • ${n.home} vs ${n.away}`;[['status',current.status],['kickoff',current.kickoff_at?new Date(current.kickoff_at).toISOString().slice(0,16):''],['venue',current.venue],['referee',current.referee],['arsenalScore',current.arsenal_score],['opponentScore',current.opponent_score],['htArsenal',current.halftime_arsenal_score],['htOpponent',current.halftime_opponent_score],['attendance',current.attendance],['addedTime',current.added_time],['motm',current.man_of_the_match]].forEach(x=>val(...x));$('motmTeam').innerHTML=$('eventTeam').innerHTML=`<option>${esc(n.home)}</option><option>${esc(n.away)}</option>`;val('motmTeam',current.man_of_the_match_team||'Arsenal');$('statsHome').textContent=n.home;$('statsAway').textContent=n.away;fields.forEach((x,i)=>{val('sh'+i,current[x[1]]);val('sa'+i,current[x[2]])});$('preview').href=`champions-league-match-details.html?match=${current.matchday-1}`;lineupTeam=n.home;$('lineupTabs').innerHTML=`<button data-team="${esc(n.home)}">${esc(n.home)}</button><button data-team="${esc(n.away)}">${esc(n.away)}</button>`;await Promise.all([loadLineups(),loadEvents(),loadTotals(),loadComparison()]);resetLineup();resetEvent();tabs();$('editor').scrollIntoView({behavior:'smooth'})}
async function recalc(id){try{const r=await window.recalculateUclStats(db);msg(id,`Saved. UCL totals recalculated from ${r.matches} completed match${r.matches===1?'':'es'} ✓`);await loadTotals()}catch(e){msg(id,`Saved, but totals failed: ${e.message}`,true)}}
$('list').onclick=e=>{const b=e.target.closest('[data-fixture]');if(b)openFixture(b.dataset.fixture)};$('close').onclick=()=>$('editor').hidden=true;
$('saveDetails').onclick=async()=>{const k=read('kickoff'),p={status:read('status'),kickoff_at:k?new Date(k).toISOString():current.kickoff_at,venue:read('venue')||null,referee:read('referee')||null,arsenal_score:num('arsenalScore'),opponent_score:num('opponentScore'),halftime_arsenal_score:num('htArsenal'),halftime_opponent_score:num('htOpponent'),attendance:num('attendance'),added_time:num('addedTime')||0,man_of_the_match:read('motm').trim()||null,man_of_the_match_team:read('motm').trim()?read('motmTeam'):null,updated_at:new Date().toISOString()};const r=await db.from('fixtures').update(p).eq('id',current.id).select('*').single();if(r.error)return msg('detailsMsg',r.error.message,true);current=r.data;await loadFixtures();await recalc('detailsMsg')};
$('saveStats').onclick=async()=>{const p={updated_at:new Date().toISOString()};fields.forEach((x,i)=>{p[x[1]]=num('sh'+i);p[x[2]]=num('sa'+i)});const r=await db.from('fixtures').update(p).eq('id',current.id).select('*').single();if(r.error)return msg('statsMsg',r.error.message,true);current=r.data;await recalc('statsMsg')};
function tabs(){$('lineupTabs').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.team===lineupTeam));renderLineups()}$('lineupTabs').onclick=e=>{const b=e.target.closest('[data-team]');if(b){lineupTeam=b.dataset.team;resetLineup();tabs()}};
async function loadLineups(){const r=await db.from('match_lineups').select('*').eq('fixture_id',current.id).order('is_starter',{ascending:false}).order('minute_on');if(r.error)return msg('lineupMsg',r.error.message,true);lineups=r.data||[];renderLineups()}
function renderLineups(){const a=lineups.filter(x=>(x.team_name||'Arsenal')===lineupTeam);$('lineupList').innerHTML=a.length?a.map(x=>`<div class="row"><strong>${x.is_starter?'STARTER':'SUB'}</strong><div><b>${esc(x.player_name)}</b><small>${esc(x.position||'')} • ${x.minute_on}'–${x.minute_off??90+Number(current.added_time||0)}'</small></div><div class="row-actions"><button data-le="${x.id}">Edit</button> <button class="danger" data-ld="${x.id}">Delete</button></div></div>`).join(''):'<div class="meta">No lineup saved for this team.</div>'}
function resetLineup(){editLineup=null;val('lineupPlayer','');val('minuteOff','');val('lineupRole','true');val('minuteOn',0);$('saveLineup').textContent='Add Player';$('cancelLineup').hidden=true}
$('saveLineup').onclick=async()=>{const name=read('lineupPlayer').trim();if(!name)return msg('lineupMsg','Player name is required.',true);const starter=read('lineupRole')==='true',p={fixture_id:current.id,team_name:lineupTeam,player_name:name,position:read('lineupPosition'),is_starter:starter,minute_on:starter?0:(num('minuteOn')??0),minute_off:num('minuteOff'),updated_at:new Date().toISOString()};const r=editLineup?await db.from('match_lineups').update(p).eq('id',editLineup):await db.from('match_lineups').upsert(p,{onConflict:'fixture_id,team_name,player_name'});if(r.error)return msg('lineupMsg',r.error.message,true);resetLineup();await loadLineups();await recalc('lineupMsg')};$('cancelLineup').onclick=resetLineup;
$('lineupList').onclick=async e=>{const eb=e.target.closest('[data-le]'),del=e.target.closest('[data-ld]');if(eb){const x=lineups.find(y=>y.id===eb.dataset.le);editLineup=x.id;lineupTeam=x.team_name||'Arsenal';val('lineupPlayer',x.player_name);val('lineupPosition',x.position);val('lineupRole',String(x.is_starter));val('minuteOn',x.minute_on);val('minuteOff',x.minute_off);$('saveLineup').textContent='Update Player';$('cancelLineup').hidden=false;tabs()}if(del&&confirm('Delete this lineup entry?')){const r=await db.from('match_lineups').delete().eq('id',del.dataset.ld);if(r.error)return msg('lineupMsg',r.error.message,true);await loadLineups();await recalc('lineupMsg')}};
async function loadEvents(){const r=await db.from('match_events').select('*').eq('fixture_id',current.id).order('minute');if(r.error)return msg('eventMsg',r.error.message,true);events=r.data||[];$('eventsList').innerHTML=events.length?events.map(x=>`<div class="row"><strong>${esc(x.event_type)}</strong><div><b>${esc(x.player_name)}</b><small>${esc(x.team_name)} • ${x.minute??'—'}${x.stoppage_minute?'+'+x.stoppage_minute:''}'${x.related_player_name?' • '+esc(x.related_player_name):''}</small></div><div class="row-actions"><button data-ee="${x.id}">Edit</button> <button class="danger" data-ed="${x.id}">Delete</button></div></div>`).join(''):'<div class="meta">No events saved.</div>'}
function resetEvent(){editEvent=null;['eventPlayer','eventMinute','eventStoppage','eventRelated'].forEach(x=>val(x,''));val('eventType','goal');$('saveEvent').textContent='Add Event';$('cancelEvent').hidden=true}
$('saveEvent').onclick=async()=>{const name=read('eventPlayer').trim();if(!name)return msg('eventMsg','Player name is required.',true);const p={fixture_id:current.id,event_type:read('eventType'),team_name:read('eventTeam'),player_name:name,minute:num('eventMinute'),stoppage_minute:num('eventStoppage'),related_player_name:read('eventRelated').trim()||null,updated_at:new Date().toISOString()};const r=editEvent?await db.from('match_events').update(p).eq('id',editEvent):await db.from('match_events').insert(p);if(r.error)return msg('eventMsg',r.error.message,true);resetEvent();await loadEvents();await recalc('eventMsg')};$('cancelEvent').onclick=resetEvent;
$('eventsList').onclick=async e=>{const eb=e.target.closest('[data-ee]'),del=e.target.closest('[data-ed]');if(eb){const x=events.find(y=>y.id===eb.dataset.ee);editEvent=x.id;val('eventType',x.event_type);val('eventTeam',x.team_name);val('eventPlayer',x.player_name);val('eventMinute',x.minute);val('eventStoppage',x.stoppage_minute);val('eventRelated',x.related_player_name);$('saveEvent').textContent='Update Event';$('cancelEvent').hidden=false}if(del&&confirm('Delete this event?')){const r=await db.from('match_events').delete().eq('id',del.dataset.ed);if(r.error)return msg('eventMsg',r.error.message,true);await loadEvents();await recalc('eventMsg')}};
async function loadTotals(){const r=await db.from('ucl_team_stats').select('*').eq('season','2026/27').order('points',{ascending:false});if(r.error)return $('totals').textContent=r.error.message;const ts=r.data||[];$('totals').innerHTML=`<h4>Teams</h4><table><tr><th>Team</th><th>MP</th><th>W-D-L</th><th>GF-GA</th><th>Pts</th><th>Poss</th><th>Shots</th><th>SOT</th><th>Corners</th><th>CG</th><th>YC-RC</th></tr>${ts.map(t=>`<tr><td>${esc(t.team_name)}</td><td>${t.matches}</td><td>${t.wins}-${t.draws}-${t.losses}</td><td>${t.goals_for}-${t.goals_against}</td><td>${t.points}</td><td>${t.matches?(Number(t.possession_total)/t.matches).toFixed(1):'0.0'}%</td><td>${t.shots}</td><td>${t.shots_on_target}</td><td>${t.corners}</td><td>${t.corner_goals}</td><td>${t.yellow_cards}-${t.red_cards}</td></tr>`).join('')}</table>`}
async function loadComparison(){const n=names(),[totals,override]=await Promise.all([db.from('ucl_team_stats').select('*').eq('season','2026/27').in('team_name',[n.home,n.away]),db.from('ucl_match_comparisons').select('*').eq('fixture_id',current.id).maybeSingle()]);if(totals.error||override.error)return msg('comparisonMsg',(totals.error||override.error).message,true);const empty=name=>({team_name:name,matches:0,wins:0,draws:0,losses:0,goals_for:0,goals_against:0,points:0,possession_total:0,shots:0,shots_on_target:0,corners:0,corner_goals:0,fouls:0,offsides:0,saves:0,yellow_cards:0,red_cards:0}),baseHome=(totals.data||[]).find(x=>x.team_name===n.home)||empty(n.home),baseAway=(totals.data||[]).find(x=>x.team_name===n.away)||empty(n.away),home={...baseHome,...(override.data?.home_stats||{})},away={...baseAway,...(override.data?.away_stats||{})};$('compareHome').textContent=n.home;$('compareAway').textContent=n.away;$('comparisonInputs').innerHTML=comparisonFields.map(([label,key,step])=>{const display=x=>key==='possession_average'?(x.matches?Number(x.possession_total||0)/Number(x.matches):0):Number(x[key]||0);return `<tr><th>${label}</th><td><input id="compareHome_${key}" type="number" min="0" step="${step}" value="${display(home)}"></td><td><input id="compareAway_${key}" type="number" min="0" step="${step}" value="${display(away)}"></td></tr>`}).join('');msg('comparisonMsg',override.data?'Saved values loaded.':'Automatic season totals loaded.')}
function readComparison(side){const row={};comparisonFields.forEach(([,key])=>{row[key]=Math.max(0,Number($(`compare${side}_${key}`).value)||0)});row.possession_total=row.possession_average*row.matches;delete row.possession_average;return row}
$('saveComparison').onclick=async()=>{const payload={fixture_id:current.id,home_stats:readComparison('Home'),away_stats:readComparison('Away'),updated_at:new Date().toISOString()},r=await db.from('ucl_match_comparisons').upsert(payload,{onConflict:'fixture_id'});if(r.error)return msg('comparisonMsg',r.error.message,true);msg('comparisonMsg','Table saved. Public win probability recalculated automatically ✓')};
$('resetComparison').onclick=async()=>{if(!confirm('Restore automatic UCL totals for this match?'))return;const r=await db.from('ucl_match_comparisons').delete().eq('fixture_id',current.id);if(r.error)return msg('comparisonMsg',r.error.message,true);await loadComparison();msg('comparisonMsg','Automatic UCL totals restored ✓')};
addSyncButton();loadFixtures();})();
